### ISSUE TITLE
Lots of Rabbit connection issues after update

### ISSUE THREAD

**Issue by mcblum** [golevelup/nestjs#104]
Hey, thanks for the awesome package. I updated to the current version, and now when I deploy and sometimes running locally I get:

```
Error: Failed to connect to a RabbitMQ broker within a timeout of 5000ms
   at AmqpConnection.init (/app/node_modules/@golevelup/nestjs-rabbitmq/lib/amqp/connection.js:59:99)
```

It'll happen a few times when deploying, those containers will fail, then a new one will spin up and eventually it will work. Any idea what's happening? I've confirmed that Rabbit is running.

**Comment by mcblum** [comment]
Also one more question, is there somewhere that describes what `externallyConfigured` does in:

```
export interface IConfigurableDynamicRootModule<T, U> {
    new (): Type<T>;
    moduleSubject: Subject<DynamicModule>;
    forRoot(moduleCtor: Type<T>, moduleConfig: U): DynamicModule;
    forRootAsync(moduleCtor: Type<T>, asyncModuleConfig: AsyncModuleConfig<U>): DynamicModule;
    externallyConfigured(moduleCtor: Type<T>, wait: number): Promise<DynamicModule>;
}
```

**Comment by WonderPanda** [comment]
Hey @mcblum I'm sorry that you've been seeing some issues since the last update. In one of the most recent updates we added support for a new wrapper around Amqp/Rabbit that gives more control over handling connects/disconnects. The default connection timeout is 5000ms which appears to be what you're running into.

You could try increasing the timeout if it's expected that it may take longer for your appliation code to negotiate a connection with your Rabbit instance.

Externally Configured is a feature of our dynamic module builder library which allows importing a module but "waiting" for it to be instantiated somewhere else. This is similar to using the @Global decorator but doesn't pollute the Module global scope. You can read a bit more about it here:

https://github.com/golevelup/nestjs/blob/master/packages/modules/README.md#one-other-option

**Comment by WonderPanda** [comment]
Closing this for now feel free to open up again if you continue to run into issues

**Comment by gialang** [comment]
@mcblum did you fix it ?
i have same issue with it.

```javascript
[Nest] 64170   - 04/13/2021, 5:24:02 PM   [AmqpConnection] Successfully connected to a RabbitMQ broker
[Nest] 64170   - 04/13/2021, 5:24:07 PM   [ExceptionHandler] Failed to connect to a RabbitMQ broker within a timeout of 5000ms +4851ms
```

**Comment by norasotanext** [comment]
> @mcblum did you fix it ? i have same issue with it.
> 
> ```js
> [Nest] 64170   - 04/13/2021, 5:24:02 PM   [AmqpConnection] Successfully connected to a RabbitMQ broker
> [Nest] 64170   - 04/13/2021, 5:24:07 PM   [ExceptionHandler] Failed to connect to a RabbitMQ broker within a timeout of 5000ms +4851ms
> ```

I increased the connection timeout and it works.

**Comment by zgid123** [comment]
Hi, I encounter this issue too. I tried to use the uri for .NET Core and it worked, but for NestJS, it didn't

```
Error: connect ECONNREFUSED ::1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
From previous event:
    at Object.connect (.../node_modules/.pnpm/amqplib@0.8.0/node_modules/amqplib/channel_api.js:6:18)
at ../node_modules/.pnpm/amqp-connection-manager@3.9.0_amqplib@0.8.0/node_modules/amqp-connection-manager/dist/cjs/AmqpConnectionManager.js:243:38
```

**Comment by zgid123** [comment]
ok, for my case, it is node 17 issue: https://github.com/amqp-node/amqplib/issues/704#issuecomment-1239434607. Use `127.0.0.1` instead of `localhost`
