### ISSUE TITLE
No way to handle failed serialization (non-json)

### ISSUE THREAD

**Issue by rennenc** [golevelup/nestjs#137]
When a non-JSON message is received (for example - via other programming language, or directly from rabbitmq management plugin), the service will not trigger the handler function, nor will throw an exception (not even globally un-handled exception). Instead, it will re-queue the message going into his infinite loop of failing and re-queuing, bombarding rabbitmq

![image](https://user-images.githubusercontent.com/61269525/80407044-a53af880-88cd-11ea-96df-df68492d6258.png)

**Comment by WonderPanda** [comment]
Hey @rennec the latest version, `@golevelup/nestjs-rabbitmq@1.15.0` introduced some changes to how errors are handled. There's some discussion and visibility around that issue here: https://github.com/golevelup/nestjs/pull/134

Basically you can opt into allowing non JSON messages with decorators like this:
```
@RabbitSubscribe({
    exchange,
    routingKey: [nonJsonRoutingKey],
    queue: 'subscribeQueue',
    allowNonJsonMessages: true,
  })
```

After this you'll have to implement your NestJS handler against the raw RabbitMQ msg which is passed as the second parameter to your handler.

There's an open effort to decouple assumptions about serialization/deserialization and allow for much better use cases that should be getting merged soon

**Comment by rennenc** [comment]
Very nice. Thanks for the update. Looking forward.

I suspect that the the motivation not to throw an error - is to avoid crashing the app; and that the motivation to re-queue the message - is to avoid data loss.

But the combination of the two leads to an infinite loop which is not ideal either.

**Comment by mariotacke** [comment]
Just ran into this also. It wasn't clear to me, from the documentation, that `allowNonJsonMessages` exists. I dug through the code when I finally found the flag. Until then, I experienced the same issue as @rennenc which worried me. IMO, it is plausible to overlook this flag and cause an "infinite" loop. Ideally, non-JSON parse-able messages should be caught globally (and optionally discarded).

Have you guys advanced on the idea yet, @WonderPanda ?

**Comment by rennenc** [comment]
That is correct if you use the default behavior. However, you can use custom serializer and then you gain full control over the serialization process and the exception handling.

**Comment by mariotacke** [comment]
Gotcha. Do you happen to have a snippet that show-cases using a custom serializer/deserializer? I can't find a reference to it in the docs.

**Comment by rennenc** [comment]
I haven't done so myself, but this seems to be such an example:
https://docs.nestjs.com/microservices/custom-transport
