### ISSUE TITLE
RabbitMQ - wrong method called

### ISSUE THREAD

**Issue by tadejgolobic** [golevelup/nestjs#141]
Hi, maybe I am missing something but this shouldn't happen

This is the code
```
@RabbitSubscribe({
    exchange: 'amq.topic',
    routingKey: 'test.create',
    queue: 'queue1'
})
public async create(message, msg) {
    console.log('ROUTING KEY CREATE: ', msg.fields.routingKey);
}

@RabbitSubscribe({
    exchange: 'amq.topic',
    routingKey: 'test.delete',
    queue: 'queue1',
})
public async delete(message, msg) {
    console.log('ROUTING KEY DELETE: ', msg.fields.routingKey);
}
```
When I publish something on amq.topic exchange, with routing key test.delete, it will print this:

ROUTING KEY CREATE:  test.delete

Is this normal? Shouldn't this call method delete?

**Comment by WonderPanda** [comment]
Yes this is expected behavior. You're reusing the same underlying queue between both subscriptions with `queue1`. You should not re-use the same queue for this as it's effectively being bound against both subscriptions. There is most likely a race condition caused by this which would allow either Nest handler to be invoked.

RabbitMQ is meant to work with many queues and they are relatively light weight. You should pretty much always create a queue per subscription unless you're specifically intending to set up a competing consumer type of pattern (eg for a shared job queue)
