### ISSUE TITLE
HasuraEventHandler not working

### ISSUE THREAD

**Issue by TheoWolf** [golevelup/nestjs#159]
Hello, 
I'm having issues with the HasuraEventHandler decorator, the hasura/events is getting the payload as expected but yet not redirecting it to the correct handler, I'm not sure if I'm doing something wrong so I will put snippets of my code. 
For the sake of simplicity, I'm putting the Hasura event handler in the same controller as the Hasura events route.
Please let me know why the code is not working as expected.
Thank you for your help

**hasura.module.ts** 
```javascript
import { Module } from '@nestjs/common'
import { HasuraController } from './hasura.controller'
import { HasuraModule as HasuraEventModule } from '@golevelup/nestjs-hasura'
import { ConfigService } from '@nestjs/config'

@Module({
  imports: [
    HasuraEventModule.forRootAsync(HasuraEventModule, {
      inject: [ConfigService],
      useFactory: async (config: ConfigService) => ({
        secretFactory: config.get<string>('HASURA_EVENT_TOKEN'),
        secretHeader: config.get<string>('HASURA_EVENT_HEADER'),
        controllerPrefix: 'hasura'
      })
    })
  ],
  controllers: [HasuraController]
})
export class HasuraModule {}
```
**hasura.controller.ts** 
```javascript
import { Controller, Session, Request, Res, Get, Post } from '@nestjs/common'
import { HasuraEventHandler, HasuraEvent } from '@golevelup/nestjs-hasura'
@Controller('hasura')
export class HasuraController {
  @Get('auth')
  async hasura(@Session() { user: { id } }, @Res() res) {
    if (!id) return res.status(401).send()

    res.json({
      'X-Hasura-Role': 'user',
      'X-Hasura-User-Id': `${id}`
    })
  }

  @Post('events')
  async handleEvents(@Request() req, @Res() res) {
   // should find the appropriate hasura event handler
    res.status(200).send()
  }

  @HasuraEventHandler({
    triggerName: 'update_user'
  })
  handleUserCreated(evt: HasuraEvent) {
    // handle the event payload.
   // this should be called automatically
  }
}
```

**Comment by n3n** [comment]
@TheoWolf You need to decorate the method in providers, not in class controller.

**Comment by TheoWolf** [comment]
@n3n Still not working even after adding a provider with @HasuraEventHandle, is there any other reason why this is not working for me.

How to make sure that my nestjs-hasura module import is working correctly, maybe Hasura is hitting the events endpoint without being processed by nestjs-hasura.

Thanks

**Comment by WonderPanda** [comment]
@TheoWolf Hey thanks for being an early adopter of the library! I think the issue here is that in addition to including the `HasuraModule` you're also creating your own `HasuraController` which uses the same `hasura` prefix as what you've given in your module configuration. The intention is that the `HasuraModule` dynamically adds its own controller for the purpose of event processing and I believe with this setup that you're overwriting it with your own Controller. We don't have plans at the moment to attempt any kind of controller "merging" 

Try changing the `controllerPrefix` in your ModuleConfig to have the provided controller use a different route scheme. You'll have to make sure that you update your Hasura event handlers to point to the correct endpoint inside your NestJS app after you do this.

Also, if you need help continuing to diagnose those maybe you could include some of the event log output from Hasura as it should give us some additional information about the response coming back to Hasura from your backend.

**Comment by TheoWolf** [comment]
@WonderPanda Thank you for your feedback, it was super helpful. Since you mentioned that the Hasura module provides a controller with a ```hasura/events``` endpoint, I just had to remove mine and apparently NestJS was able to merge both controllers. It is not clear in the documentation that the Hasura module provides a default controller with a default implementation of ```hasura/events``` and it would be great to have it in the Readme file. I will put the working code here for future reference. Thank you for the amazing work and support.

**hasura.module.ts**
```javascript
import { Module } from '@nestjs/common'
import { HasuraController } from './hasura.controller'
import { HasuraModule as HasuraEventModule } from '@golevelup/nestjs-hasura'
import { ConfigService } from '@nestjs/config'

@Module({
  imports: [
    HasuraEventModule.forRootAsync(HasuraEventModule, {
      inject: [ConfigService],
      useFactory: async (config: ConfigService) => ({
        secretFactory: config.get<string>('HASURA_EVENT_TOKEN'),
        secretHeader: config.get<string>('HASURA_EVENT_HEADER'),
      })
    })
  ],
  controllers: [HasuraController]
})
export class HasuraModule {}
```

**hasura.controller.ts**
```javascript
import { Controller, Session, Request, Res, Get, Post } from '@nestjs/common'

@Controller('hasura')
export class HasuraController {
  @Get('auth')
  async hasura(@Session() { user: { id } }, @Res() res) {
    if (!id) return res.status(401).send()

    res.json({
      'X-Hasura-Role': 'user',
      'X-Hasura-User-Id': `${id}`
    })
  }
}
```

**hasura.service.ts**
```javascript
import { Injectable } from '@nestjs/common'
import { HasuraEventHandler, HasuraEvent } from '@golevelup/nestjs-hasura'

@Injectable()
export class HasuraService {
  @HasuraEventHandler({
    triggerName: 'update_user'
  })
  handleUserCreated(evt: HasuraEvent) {
    // handle the event payload. Typing the method parameter with `HasurEvent` will provide intellisense
  }
}
```

**Comment by WonderPanda** [comment]
Hey thanks for the feedback @TheoWolf! The first feature from the docs says:

"Exposes an API endpoint from your NestJS application at to be used for event processing from Hasura. Defaults to `/hasura/events/` but can be easily configured"

The intention was to communicate that this happens automatically but I realize that this the way this is worded is a bit ambiguous. I'll update the docs so that it's more obvious for future users that the Controller is provided for them.

Please feel free to continue to open issues for problems you run into as well as feature requests in this area as I believe that NestJS and Hasura have huge potential together! The feedback from you and @n3n is super valuable and appreciated
