### ISSUE TITLE
Unexpected return from a matcher function.

### ISSUE THREAD

**Issue by dsfcoll** [golevelup/nestjs#160]
I have an issue with `@golevelup/nestjs-testing package`.

I have a test 
```js
import { createMock } from "@golevelup/nestjs-testing";
...
it ('should get one by email', async () => {
    const mockedUser = { email: 'test@mail.ru', username: 'test', password: '1234567', name: 'Test' };
    jest.spyOn(model, 'findOne').mockResolvedValueOnce(createMock<UserDoc>(mockedUser));
    const user = await service.findByEmail('email@mail.ru');

    expect(user).toEqual(mockedUser);
});
```

And jest throws exception 

```
Unexpected return from a matcher function.
    Matcher functions should return an object in the following format:
      {message?: string | function, pass: boolean}
    '{"actual": {"user": {}}, "expected": {"user": {"email": "email@mail.ru"}}, "message": [Function anonymous], "name": "toEqual", "pass": {}}' was returned
```

But if i replace type to `any`, it works
```js
jest.spyOn(model, 'findOne').mockResolvedValueOnce(mockedUser as any);
```

**Comment by WonderPanda** [comment]
Hey @VladStepanov just want to make sure I understand correctly. You're saying that you get this error message when you run the test, but after switching to using `any` the jest error goes away?

Are you able to share a repo or complete code example that demonstrates this behavior? It's really strange if changing a TS type definition causes the test to behave different since the Jest error is a runtime thing which isn't affected by TS types

**Comment by dsfcoll** [comment]
@WonderPanda ofc, https://github.com/VladStepanov/reproduction

**Comment by WonderPanda** [comment]
Hey @VladStepanov I took a look at your reproduction, there are a couple things I suggest you change. One thing is that you're referencing an old version of the library. It got changed a while back to be called `@golevelup/ts-jest` as it's a generic tool for helping do Jest testing with Typescript and isn't specific to NestJS. The other thing is that you shouldn't use `createMock` to set up the return values of functions. The idea is to use `createMock` to create the services under your control. I've updated your test to show you:

``` typescript
import { Test, TestingModule } from '@nestjs/testing';
import { getModelToken } from '@nestjs/mongoose';
import { createMock } from '@golevelup/ts-jest';
import { Model } from 'mongoose';
import { AppService } from './app.service';
import { UserDoc, User } from './User.schema';

describe('', () => {
  let module: TestingModule;
  let service: AppService;
  let model: Model<UserDoc>;
  
  const mockedUser: User = { username: 'Some username', email: '1@mail.ru' };

  beforeEach(async () => {
    module = await Test.createTestingModule({
      providers: [
        AppService,
        {
          provide: getModelToken('User'),
          useValue: createMock<Model<UserDoc>>({
            findOne: async () => mockedUser as any
          })
        }
      ],
    }).compile();

    service = module.get(AppService);;
  })

  it ('createMock usage', async () => {
    const mockedUser: User = { username: 'Some username', email: '1@mail.ru' };
    const foundUser = await service.getUserByEmail(mockedUser.email);
    expect(foundUser).toEqual(mockedUser);
  })
})
```
Note that the `useValue` is leveraging `createMock` instead of trying to provide a mock in `mockResolvedValueOnce`. This would never have evaluated to be equal.

You shouldn't need to use `spys` on the the Model as the mock for `Model<UserDoc>` is already set up through the `useValue` providing the mock during the creation of the Test Module.

I'm going to close this issue but feel free to continue discussion here if you need more clarification
