### ISSUE TITLE
[RabbitMQ] Strange behaviour of @RabbitSubscribe

### ISSUE THREAD

**Issue by htndev** [golevelup/nestjs#223]
When I use a few ``@RabbitSubbscibe``, it has strange behavior.
Handler 1.
![image](https://user-images.githubusercontent.com/29665511/105895449-34706a80-601e-11eb-841d-1cad51501c63.png)
Handler 2.
![image](https://user-images.githubusercontent.com/29665511/105895550-51a53900-601e-11eb-8f2a-8db52e41a62e.png)
When I am publishing a message, it reacting one by one, *BUT* it has different routing keys.
![image](https://user-images.githubusercontent.com/29665511/105895756-9335e400-601e-11eb-9321-e0a583d9030c.png)
Console output
![image](https://user-images.githubusercontent.com/29665511/105895802-a5178700-601e-11eb-90b8-40485264124f.png)

Is it an error or expected behavior?

**Comment by htndev** [comment]
One more comment.
If I subscribe on 2 different queues, it will work fine.
From the [documentation](https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/README.md#competing-consumers), I got that If I want to avoid this behavior, I don't need to provide a ``queue``option.
Why does round-robin apply to different routing keys?

**Comment by WonderPanda** [comment]
It's important to understand that in RabbitMQ a `queue` is its own destination for messages. A queue can be bound to multiple routing keys and even multiple application subscribers. When you re-use the same queue across multiple routing keys any messages sent to any of the matching routes will arrive at your handler.

This is a common point of confusion with people new to RabbitMQ so I might try and put together a visual diagram and add it to the docs to help explain better.

The main takeaway is don't re-use the same queue name across multiple routing keys unless you actually want to receive messages from all of them to the same handler

**Comment by htndev** [comment]
@WonderPanda thanks for your explanation! I want you to answer my question: If I create a consumer without providing a ``queue``, will my messages store after disconnect? (exclusive queue)

**Comment by WonderPanda** [comment]
@htndev If you do not provide a queue name, a random queue name will be assigned to your handler while NestJS is bootstrapping. This means that if your application is restarted it will create a new random queue to use. For this reason it is strongly encouraged that you always provide a logical queue name so that the same queue can be attached back to the handler on each application restart.

In the screenshot below you can see multiple queues starting with `amq.gen` from the different times that the application was restarted. Each one retrains all the messages it has received so it is recommended you always use good queue names

![example-rabbit-exchange](https://user-images.githubusercontent.com/3631771/106525824-93b4fb80-64b2-11eb-8e45-983e7949a167.png)

There are probably very few reasons why you would want to have an auto generated queue name.

By default all queues are created as *durable* which means they will persist messages that have been captured and not processed. You can override it by setting the `queueOptions` in your decorator.
