### ISSUE TITLE
How to set response message contentType from rpcHandler?

### ISSUE THREAD

**Issue by igorz24** [golevelup/nestjs#228]
Hi, 

I'm integrating two microservices written in NodeJS and Java. I have trouble in making both communicate, because Spring AMQP handler expects to receive "application/json" message from Node RPC Handler. As far as I understand it, the content actually is buffered as a JSON message, however, I cannot set the appropriate header for the returned message.

I would like to be able to set the headers (options) while returning a response from RPC Handler as specified in the [publish API](http://www.squaremobius.net/amqp.node/channel_api.html#channel_publish).

Looking at the source code, I see that the options object is passed as an argument, but I cannot find where to pass my own values:
![image](https://user-images.githubusercontent.com/14991847/106452598-6bb0a280-6488-11eb-83ee-ddfc4c16f371.png)

Here's my method, from which I want to return the message with specified contentType header:
![image](https://user-images.githubusercontent.com/14991847/106452722-8f73e880-6488-11eb-980a-a03c24ae5d25.png)

**Comment by WonderPanda** [comment]
It isn't really possible to do this today. I'm starting to consider the roadmap for v2.0 which might fix this and a lot of other issues. Please consider sharing some ideas you have for how you would like this feature to work over at https://github.com/golevelup/nestjs/discussions/227.

Some ideas that come to mind:
- should it be a new function that you add to the decorator?
- would you like to return a "special" object from  the `getUser` function which will allow for attaching additional optional options for each response sent over RPC?

Please let me know what you think so that I can properly determine the roadmap

**Comment by igorz24** [comment]
I'll join the conversation and move the discussion there.
