### ISSUE TITLE
[Question] Is it possible to just define connection without queues/exchanges and then define them later?

### ISSUE THREAD

**Issue by Setitch** [golevelup/nestjs#231]
I want to make application (which will be growing) and i dont know each exchange nor queues each module will use. I would love to define some basic queues/exchanges but i would love to be able to add them (define) at later time (onModuleInit for example). Is there a way to do this now?

**Comment by underfisk** [comment]
You can provide an empty array, yes but if it tries to connect it would not be able to because there is no exchange therefore i advise you to create a default exchange and use it anytime you need
Now if the question is related to defining later, you can define later using amq connection (after injecting it)
Another alternative is to use a factory for the module using forAsyncRoot

**Comment by WonderPanda** [comment]
@Setitch RabbitMQ has the ability to assert exchanges and queues in an `idempotent` way, which means that if the exchange or queue already exists, nothing happens if you attempt to create it again.

For this reason, you can slowly add queues/exchanges to module configuration overtime and they will be automatically created if they don't exist yet as part of the normal start up process of the Module.

**Comment by Setitch** [comment]
Thank you All for answers, i was just curious if ability to do that is available by some Decorators or i am to do that by hand. Now i know i would need to make that by hand and directly using connection service.

**Comment by WonderPanda** [comment]
@Setitch You shouldn't have to do it by hand, just add them to the Module Options as you decide what your exchanges should be and then they will automatically be created if they don't exist next time the app starts up

**Comment by Setitch** [comment]
Then i would need to define all exchanges up front (what if i have modular and plugin architechture - and i dont know them at the moment is providing queue module, only after (in modules that use this one?)

**Comment by WonderPanda** [comment]
Yeah if you want it to be dynamic/plugin based you can do it by just injecting AmqpConnection and calling its methods directly
