### ISSUE TITLE
StripeModule providers unavailable in other modules

### ISSUE THREAD

**Issue by HMilbradt** [golevelup/nestjs#238]
I'm currently creating the StripeModule with `StripeModule.forRoot()`.  This is done inside my AppModule.

However, I've noticed that the Stripe client isn't available in other dependant modules.  I didn't see a `global` property being set anywhere in the source, so I'm curious if there's a recommended method for using the Stripe client in other modules.

For reference, I'm importing the StripeModule, plus several other modules that need the Stripe client, within my AppModule.

Thanks!

**Comment by HMilbradt** [comment]
Follow up:

I just remembered that the return value of the `forRoot()` function is itself a module config, so I've just gone and manually set `global` to true on it.  I'm assuming there's a better way to handle this, but this will work for the short term.

**Comment by WonderPanda** [comment]
Generally I'd recommend wrapping your own Module around third party ones so that you can control what providers you want to re-export and make available to other parts of your application. That way you can selectively import your own module eg `PaymentsModule` (which wraps Stripe) and anything that needs it can import it. I try to stay away from Global modules/providers unless its really necessary
