### ISSUE TITLE
[Discovery] allow to pass a function or a MetaKey

### ISSUE THREAD

**Issue by adrien2p** [golevelup/nestjs#24]
Hey,

It could be nice to pass a filter function for the metaKey in order to be able to get all the target which respect the result of that function.

For example: 

`AND`
```ts
await discoveryService.providersWithMetaAtKey(metaKeys => !difference(['key1', 'key2'], metaKeys).length);
```

`OR`
```ts
await discoveryService.providersWithMetaAtKey(metaKeys => metaKeys.some(k => k === 'key1' || k === 'key2'));
```

what do you think about that ?

**Comment by WonderPanda** [comment]
I think that this makes a lot of sense. There are quite a few use cases where it would be nice to return multiple providers or controllers with different meta keys. The core functionality for this should already be present by using the higher level filtering functions (instead of the metaKey focused functions). However, since the most common use case is querying dependencies that have specific meta I think it might warrant baking that into the core API

**Comment by adrien2p** [comment]
Do you mean, `async providers` and pass `withMetaAtKey` for example ?

**Comment by WonderPanda** [comment]
Yeah the library already exposes the more low level `providers` method:
```typescript
/**
   * Discovers all providers in a Nest App that match a filter
   * @param providerFilter
   */
  async providers(filter: Filter<DiscoveredClass>): Promise<DiscoveredClass[]> {
    return (await this.discoveredProviders).filter(x => filter(x));
  }
```

This could be combined with `withMetaAtKey` as you've already identified to give the functionality that you're looking for. However, I feel that this use case is common enough that it would probably be beneficial to bake it right into the API instead of requiring users to build their own

**Comment by adrien2p** [comment]
Great 👍
