### ISSUE TITLE
amqp pub/sub throws exception on every message

### ISSUE THREAD

**Issue by michaelkrone** [golevelup/nestjs#3]
Hi,

I am evaluating solutions for using an amqp broker with Nest.js and your project looks very promising.

I tried the pub/sub feature by adapting your kitchen-sink example and it works well, but I noticed that the timeout Exception is thrown on every message:
```
UnhandledPromiseRejectionWarning: Error: Failed to receive response within timeout of 10000ms
    at MapSubscriber.rxjs_1.interval.pipe.operators_1.map.x [as project] (/Users/mkrone/Development/nestjs-plus/examples/kitchen-sink/node_modules/@nestjs-plus/rabbitmq/src/amqp/AmqpConnection.ts:79:15)
```

Maybe the use of rxjs `timeout` or `takeUntil` operators can fix this in packages/rabbitmq/src/amqp/AmqpConnection.ts?

Let me know if I can help out with this.

**Comment by WonderPanda** [comment]
Hey @michaelkrone thanks for checking out the project. Out of curiosity what version of the package are you currently referencing? I believe that there was an issue with the timeout which I've already fixed up. I don't see the same behavior when using RPC in the `kitchen-sink` example.

The steps I'm taking are to start up Rabbit using the docker-compose file in the Kitchen Sink project (`docker-compose up -d`) and then to run the application using `yarn start`. After that if you view `localhost:3000/messaging` you should get a JSON response (which is retrieved through the RMQ exchange) and there shouldn't be any timeout error messages received.

Also, if during your investigation you notice any other issues that might otherwise prevent you from adopting please let me know as I'm engaged and motivated to make the developer experience as pleasing as possible.

**Comment by WonderPanda** [comment]
I did just notice that the Kitchen Sink example was referencing an older version of the `@nestjs-plus/rabbitmq` package and I've updated it to latest with https://github.com/WonderPanda/nestjs-plus/pull/4 but even on the earlier version it doesn't have the timeout issue you're referencing.

**Comment by michaelkrone** [comment]
Hi @WonderPanda , thank you for your quick response.
You are right, the RPC example is working fine. I looked up my changes and it turned out I used `connection.request` when I meant to use `connection.publish`, so the Timeout Exception is completely valid in that case.

I will close this Issue, sorry for any inconveniences.

P.S.
One thing I am investigating is when adding a second exchange with type 'fanout', the management console lists it with the correct type, but the following exception is thrown at startup:
```
Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'exchange2' in vhost '/': received 'topic' but current is 'fanout'"
```
I will open another Issue if this turns out to be a problem, but I will make sure that this time it's not my incompetence that takes your time ;)

**Comment by WonderPanda** [comment]
@michaelkrone  No problem! It just makes me happy that people are starting to check things out. I will definitely look into the different exchange types and see if there's something going on there.

One thing that is somewhat strange is that the intention for RPC is that you *would* use the request method as you're setting up a listener internally to get the response from the RPC handler. So it's a little weird about publish as that one is more intended for Pub/Sub scenarios. Are you able to share the repository or a small example that reproduces your setup so I can make sure that it's what you need?

**Comment by WonderPanda** [comment]
@michaelkrone You were correct, there's a bug in the way subscribers are attached when using exchange types other than `topic`. I've opened an issue to track it https://github.com/WonderPanda/nestjs-plus/issues/5

It should be a small tweak so I'll get the fix up this weekend

**Comment by WonderPanda** [comment]
@michaelkrone #5 is now closed and I've updated the kitchen sink example app. Should be fine to use the different exchanges types now
