### ISSUE TITLE
Question about RmqSubscribe handler and serial message pattern

### ISSUE THREAD

**Issue by gallak87** [golevelup/nestjs#308]
Hi - is there any example pattern to have a subscribe handler process messages synchronously based on some hash?

I can think of a way to do it with a thread pool, basically grab the message, hash the id with a modulo 3 for example, and have a thread consuming each of the buckets to synchronously handle this message - but before I implement this by hand in my typescript pkg, I was wondering if the RMQ subscribe handler has any common mechanism/pattern designed for this? Is it achievable with something like a routing key with wildcard?

Note that I don't want to simply make the RMQ handler method synchronous, that would make it so _every_ message is processed serially, I want to process messages serially only based on a hash of an ID

**Comment by WonderPanda** [comment]
No existing functionality exists in the current package for this. To be honest, I've never heard of someone trying to accomplish something like this before inside the handlers.

Could you use https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange instead and then just limit the count of retrieved messages on the consumer to 1 so that it is processed synchronously?

**Comment by WonderPanda** [comment]
Closing for lack of information right now. Feel free to reopen if you have a chance to look at the consistent hash exchange or provide some more information about what's needed here
