### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by jasperblues** [golevelup/nestjs#42]
For caching, I created: https://www.npmjs.com/package/typescript-cacheable
^-- Take a look, perhaps it can help?

**Comment by WonderPanda** [comment]
Hey @jasperblues thanks for your continued participation in issues for this repository. I'm trying to determine my plans for where to take nestjs-plus next and at the moment I think that my focus is going to be on more microservice transport/communcation packages as I feel that there's still a big gap here.

For that reason I'm going to close this for now since I don't anticipate spending much time on caching in the near future however I'm always open to contributions if you wanted to take a crack at adding this functionality in

**Comment by jasperblues** [comment]
https://github.com/liberation-data/drivine

^-- Hey @WonderPanda here's my current Nest related work. Currently Nest is integral, however I'll likely make it an optional dependency. 

Also (privately, for a client) wrote a scheduler module that uses your lib.
