### ISSUE TITLE
See what scope the parent provider/controller of the discovered method is? 

### ISSUE THREAD

**Issue by jasperblues** [golevelup/nestjs#43]
Is it possible to see what scope the parent provider/controller of the discovered method is?

**Comment by WonderPanda** [comment]
Are you referring to Singleton, Request or Transient Scopes in the context of the Discovery Service?

**Comment by jasperblues** [comment]
> Are you referring to Singleton, Request or Transient Scopes in the context of the Discovery Service?

Yes wondering if possible to know the scope of discovered providers or controllers? 

I believe the data is in the underlying NestJS framework. This is a fantastic library btw! The same code without the library gets quite tedious.

**Comment by WonderPanda** [comment]
@jasperblues Sorry for the delayed response, I've been on vacation this past week. Currently it is only possible to discover Singleton services as the discovery service works by integrating with the Module Initialization lifecycle hook. During this time these are the only dependencies that can actually be resolved from the container.

Request scoped dependencies are explicitly filtered out because given the use case that this library supports it doesn't really make sense to get an instance of one. I'm open to the possibility of trying to expand functionality around non singleton dependencies though if there's new and interesting use cases that this would open up.

I'm glad you're enjoying the library so far, do you mind expanding a bit on what you're currently using it for and how accessing these other scopes might be helpful?

**Comment by WonderPanda** [comment]
@jasperblues I'm going to close this for now. Feel free to continue the conversation from my previous comment

**Comment by jasperblues** [comment]
> @jasperblues Sorry for the delayed response, I've been on vacation this past week. Currently it is only possible to discover Singleton services as the discovery service works by integrating with the Module Initialization lifecycle hook. During this time these are the only dependencies that can actually be resolved from the container.

I wanted to ensure that my decorator based job scheduler only applied to singletons, so this meets my needs. Thanks a lot for the response, and again for the excellent library.
