### ISSUE TITLE
Can @RabbitSubscribe decorator be created with dynamic exchange/queue by a factory or config ?

### ISSUE THREAD

**Issue by ilanl** [golevelup/nestjs#439]
I would like to ensure isolation for multi tenant platform
The naive way would be to have different exchange/routing/queue for tenant.
Can a decorator have a configuration injected to it?

How should I approach this? I'm open to suggestion kinda of new to RabbitMQ.

```
@RabbitSubscribe({
    exchange: 'topic-exchange', //  should be a dynamic key from factory/config
    routingKey: 'inbound', //  should be a dynamic key from factory/config
    queue: 'inbound-queue', // should be a dynamic key from factory/config
  })
  pubSubHandler(msg: unknown): void {
    console.log(`Received message: ${JSON.stringify(msg)}`);

  }
```

**Comment by WonderPanda** [comment]
It is not possible to read values from a ConfigService to pass to decorators because decorator code is executed the moment the file is imported, which is well before any of the NestJS modules could be bootstrapped.

You can dynamically configure decorators by reading configuration from Environment Variables at application startup but you'll have to do it manually due to the limitations above
