### ISSUE TITLE
Question about listening to an exchange but using the service queue

### ISSUE THREAD

**Issue by mcblum** [golevelup/nestjs#45]
Hey, sorry if I'm misunderstanding how Rabbit is supposed to work. Right now we're creating an exchange for each event and that should route to one or more service queues. So `CreateUserEvent` routes to `user-service-queue` and `logger-service-queue`. In our Nest module, we're listening to that event. If I create a listener and specify the exchange and the queue, the underlying function ends up being triggered on every message that comes into the queue, even if it didn't come from that exchange. If I omit the queue in the listener decorator, that specific function will create its own default queue.

Is there a way to only use the 4 main service queues while listening for messages which originated from `CreateUserEvent` and were routed to `user-service-queue`? Am I missing something / doing something dumb here?

**Comment by mcblum** [comment]
Ok one more question, kind of related to this. I've testing adding queue names to the listeners. Here's what I have:

`@RabbitRPC(rpcListenerFromEvent(CreateCallEvent, RABBIT_QUEUES.CHAT_SERVICE))`

and in the same class:

`@RabbitRPC(rpcListenerFromEvent(LoadMessagesEvent, RABBIT_QUEUES.CHAT_SERVICE))`

and my helper function:
```
export function rpcListenerFromEvent(
  event: any,
  queue?: string,
  queueOptions?: QueueOptions,
  errorBehavior?: MessageHandlerErrorBehavior
): MessageHandlerOptions {
  const e = new event();
  return {
    exchange: e.exchange,
    routingKey: e.routingKey,
    queue,
    queueOptions,
    errorBehavior
  };
}
```

So the strange thing about this is that the function for `LoadMessagesEvent` fires when I dispatch a `CreateCallEvent` message. If I don't specify a queue name, then the correct handler function does fire but also there are like 1000 temporary queues created. Do you have any insight as to why that might be happening?

**Comment by mcblum** [comment]
Hey, me again, sorry to be so annoying. Maybe these ramblings will help someone else understand everything at some point. So I think I'm getting that you really want an RPC handler function which then calls the appropriate sub-function. What I'm wondering is how to do that. I currently have this, which doesn't work:
```
@RabbitRPC(rpcListenerFromEvent(LoadMessagesEvent, RABBIT_QUEUES.CHAT_SERVICE))
    @RabbitRPC(rpcListenerFromEvent(SendMessageEvent, RABBIT_QUEUES.CHAT_SERVICE))
    @RabbitRPC(rpcListenerFromEvent(CreateRoomEvent, RABBIT_QUEUES.CHAT_SERVICE))
    @RabbitRPC(rpcListenerFromEvent(CreateCallEvent, RABBIT_QUEUES.CHAT_SERVICE))
    @RabbitRPC(rpcListenerFromEvent(GetAuthorizedRoomsForUser, RABBIT_QUEUES.CHAT_SERVICE))
    public async rpcHandler(payload: any, message: any) {
        console.log('handle');
        let handler;
        switch (message.fields.exchange) {
            case LoadMessagesEvent.exchange: {
                handler = this.messageService.loadMessages;
                break;
            }
            
            case SendMessageEvent.exchange: {
                handler = this.messageService.createRoom;
                break;
            }
            
            case CreateRoomEvent.exchange: {
                handler = this.roomsService.createRoom;
                break;
            }
            
            case GetAuthorizedRoomsForUser.exchange: {
                handler = this.roomsService.getAuthorizedRoomsForUser;
                break;
            }
            
            case CreateCallEvent.exchange: {
                handler = this.callService.create;
                break;
            }
            
            default: {
                throw new Error(`Unhandled event in Chat Service with type: ${message.fields.exchange}`);
            }
        }

        return await handler(payload, message);
    }
```
I know I must be missing something here...

**Comment by WonderPanda** [comment]
Hey @mcblum No need to apologize, you're not annoying. I appreciate you filling in these tickets with detail as it can definitely be helpful for others in the future.

The intended design pattern from how I myself use the library is to have individual service classes (classes decorated with @Injectable) that have appropriate methods on them wired to the processing of a single message. Right now it feels like you're strongly violating the Single Responsibility Principle by having a single handler like this. It's a bit of a code smell to have to continuously come back and add more stuff to your switch case.

I think that it's good to think about Rabbit communication similar to API controllers. You wouldn't write an API controller that responded to every type of message and HTTP Verb and then had a big switch case inside. Your code will be much more maintainable if you split things out so that they're grouped by use case.

Reading your code snippet it seems like you already have these types of services in your application. You should be decorating the service methods directly so that they can be directly invoked by Rabbit messages instead of manually passing them through like this. For example, `roomsService.createRoom` should have the Rabbit decorators directly on it.

**Comment by mcblum** [comment]
@WonderPanda hey! I totally agree - the issue was that having a handler function for each exchange / queue combination wasn't really working. I checked the source and it looks like when `createRpc` is called it then listens to the queue and calls the handler but it doesn't actually check to see if the exchange matches the exchange that was passed in to the decorator. So what ends up happening is that any handler function where a queue is defined fires for all messages placed in that queue, no matter which exchange was specified. Do you see that, too, or am I missing something?

**Comment by mcblum** [comment]
In case that isn't actually clear, what I had was what you'd expect:

```
@RabbitRPC({exchange: 'EX1', queue: 'chat_service'})
async handlerOne() {
   return 1;
}

@RabbitRPC({exchange: 'EX2', queue: 'chat_service'})
async handlerTwo() {
   return 2;
}
```

So I would dispatch a message on `EX1` and get `2` as the response. The reason (I believe) was because there wasn't ever a comparison happening of `message.fields.exchange === exchange` to see which handler function should fire, it was always just firing the last one that was registered in order. Does this make sense?

**Comment by WonderPanda** [comment]
Are you trying to reuse the same queue name in multiple places? I think there might be some misunderstanding here. Queue names are equivalent to identity in Rabbit. Consider this code from createRpc:

```
const { queue } = await this.channel.assertQueue(rpcOptions.queue || '');
await this.channel.bindQueue(queue, exchange, routingKey);
```

This ensures that a named queue is created and then it binds that queue to the exchange + routing key combination. 

Then, we attach a listener to the queue so that messages coming off of it can be processed in app by the provided handler:

```
await this.channel.consume(queue, async msg => {
      // do stuff
```

If you use the same queueName with multiple exchanges and routing keys then the library will happily bind those to the queue as well which means it will be processing messages off of all of them. There's nothing inside of Rabbit that would override a previous binding if a new one was provided and I wouldn't want to put protections in to prevent people from doing this as there could be valid use cases for it.

In this case, you should use different queue names for your individual handlers (why are you combining them anyways?) or, we pass the raw AMQP message as the second parameter to your supplied handler so if you want you could include your own logic to check the exchange value and opt out of processing the message

**Comment by WonderPanda** [comment]
In your code example:
```
@RabbitRPC({exchange: 'EX1', queue: 'chat_service'})
async handlerOne() {
   return 1;
}

@RabbitRPC({exchange: 'EX2', queue: 'chat_service'})
async handlerTwo() {
   return 2;
}
```

Both handlers will receive all messages from both exchanges because they're bound to the same queue. This is just a feature of how RabbitMQ works it's up to you to pick the correct queue names to isolate messaging workloads.

If you want to isolate them by exchange you could just make the queue names something like  `ex1_chat_service` and `ex2_chat_service`

**Comment by mcblum** [comment]
@WonderPanda yes, I think that's where I'm off. I assumed that there was, essentially, one queue per service and that the exchange or routing key was used to determine where things went within your handlers. So are you saying that if I have something like `CreateRoom` that I should have a `CreateRoom` exchange that routes to a `CreateRoom` queue specifically? I had envisioned that it would be less resource-intensive to have one queue for each service. Clearly I'm missing some information here :)

So that would mean that for each unique task I'd have, at least, a unique exchange and one unique queue. Then if other services needed to know, say, about `CreateRoom` I would make additional queues like `log_service_create_room`?

**Comment by mcblum** [comment]
Thank you for taking the time to talk this through, clearly I wasn't envisioning using Rabbit as it was intended. I'm a FE dev so I was treating this like backend Redux :)

**Comment by WonderPanda** [comment]
No worries. Exchanges and Routing Keys are definitely used to route messages to their intended listeners but ultimately you need to have a queue to facilitate that delivery and queues are based on that identity concept (a named queue could be bound to multiple things). Queues are not super expensive to have in RabbitMQ I definitely wouldn't recommend structuring your app to try to force all traffic through only one queue for example.

I personally feel like a `CreateRoom` exchange feels way too granular. If it were me I'd probably have a `Room` exchange so that all messages related to that specific entity flow through one exchange and then individual queues for different actions. `create_room_queue`, `get_room_queue`, `update_room_queue` etc would glue your service method directly to the processing of that message instead of having a switch case that does an extra layer of routing to your service methods

**Comment by mcblum** [comment]
@WonderPanda brilliant. I was copying the pattern that I saw at one of my last gigs where there was, essentially, one Exchange per event. I like your pattern better and I'll do just that.

Really, really appreciate the effort and let me know if I can send over some bitcoin for a beer or something.

**Comment by WonderPanda** [comment]
Ahaha, if you feel like sending some bitcoin I'll definitely take it but I'm also happy to help out. Feel free to keep asking questions I definitely think it's worthwhile having history of these kinds of things for other people to reference. Cheers

3Gbf5Gmr79t2Db3FsbJwDBmog6cw7tqdcf (BTC Address)
