### ISSUE TITLE
[RabbitMQ] How should be main.ts ?

### ISSUE THREAD

**Issue by fbaldo31** [golevelup/nestjs#47]
Hi, i have few questions regarding the install / usage of the package :
Can you add to your documentation an example of the main.ts file please ?
Do we need @nestjs/microservice package ?

In fact i don't how to start, a full example would be really appreciate (or at least the minimum dependecies & main.ts example).

**Comment by WonderPanda** [comment]
Hi @fbaldo31 
This project offers the `examples/kitchen-sink` directory which contains a Nest App that's set up with RabbitMQ and shows off some basic functionality. In addition, there are integration tests (tests that talk to a real RabbitMQ service) which also demonstrate how to set up RabbitMQ in your NestJS app.

https://github.com/WonderPanda/nestjs-plus/blob/master/examples/kitchen-sink/src/rabbit-example/rabbit-example.module.ts

You don't need the @nestjs/microservice package in order to use this.

Feel free to pull this repository down and explore the various samples and tests.

**Comment by fbaldo31** [comment]
Thank you for quick answer it is clear now
