### ISSUE TITLE
RPCException problem sending error message between services 

### ISSUE THREAD

**Issue by ethirion** [golevelup/nestjs#509]
I have 2 services, one producer and another one consumer. i created an RPCException in consumer to test it.when the producer service sending a RPC message to consumer and consumer service throw a RPCException, i expected an object with error message in result of rpc request from producer service, but i got empty object {}. my problem is that response message from consumer is empty object but i expected an object with error code or error message.

producer main.ts: 
```
import { NestFactory } from '@nestjs/core';
import { ApiGatewayConfigService } from './api-gateway.config.service';
import { ApiGatewayModule } from './api-gateway.module';
import * as sourceMapSupport from 'source-map-support';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { ValidationPipe } from '@nestjs/common';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import { ExceptionFilter } from '@shared/shared/rpc-exception.filter';

async function bootstrap() {
  sourceMapSupport.install();
  const app = await NestFactory.create<NestFastifyApplication>(
    ApiGatewayModule,
    new FastifyAdapter()
  );

  const configService = app.get(ApiGatewayConfigService);

  app.useGlobalFilters(new ExceptionFilter());
  app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
      transformOptions: {
        enableImplicitConversion: true
      },
      whitelist: true,
      forbidNonWhitelisted: true,
      disableErrorMessages: configService.APP_ENVIRONMENT === 'production'
    })
  );
  app.enableShutdownHooks();
  await app.listen(configService.APP_LISTENING_PORT, '0.0.0.0');
}
bootstrap();
```
producer service:
```
  async page(privileges: UserPrivileges, acceptLanguage: string): Promise<any> {

      const result = await this.amqpConnection.request<any>({
        exchange: process.env.API_GATEWAY_RABBITMQ_EXCHANGE_NAME,
        routingKey: 'trend_specific_test',
        payload: {
          options:{
            from: 0,
            limit: 21,
            privileges
          },
          acceptLanguage
        },
      });

      console.log(result);
  }
```

consumer service:
```
import { NestFactory } from '@nestjs/core';
import { TrendModule } from './trend.module';

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(TrendModule);
}
bootstrap();

```

consumer service:
```
    @UseFilters(new ExceptionFilter())
    @RabbitRPC({
        exchange: RABBITMQ_EXCHANGE_NAME,
        routingKey: 'trend_specific_test',
        queue: 'trend_specific_test',
        allowNonJsonMessages: true,
    })
    async dailyPlaylists(msg: {options: SearchOptions, acceptLanguage: string}): Promise<any> {
        return this.trendDataService.testMethod(msg.options, msg.acceptLanguage);
    }
```

consumer data service:
```
  async testMethod(options: SearchOptions, acceptLanguage: string): Promise<any> {
    throw new RpcException('Invalid credentials.');
}
```
rpc-exception.filter.ts
```
import { Catch, RpcExceptionFilter, ArgumentsHost } from '@nestjs/common';
import { Observable, throwError } from 'rxjs';
import { RpcException } from '@nestjs/microservices';

@Catch(RpcException)
export class ExceptionFilter implements RpcExceptionFilter<RpcException> {
  catch(exception: RpcException, host: ArgumentsHost): Observable<any> {
    return throwError(() => exception.getError());
  }
}
```

**Comment by SevenWaysDP** [comment]
I have the same problem and I can't catch it

**Comment by silviobig96** [comment]
any update on this? i want to catch the error and log the error, i couldn't find a way to do that.

**Comment by Lormida** [comment]
Probably i'm completely wrong in it, but i can describe how i handle errors between microservices with RabbitMQ.
1. I use `api gateway pattern` this means i have single http entrypoint controller which redirect my initial requests to another microservices using RabbitMq. My workflow looks like:

(1) Controller gets http request -> (2) Forward this request via rabbitMq to another ms -> (3) This ms can either forward new request to another ms via rabbitmq or return result.
1. In the 
 @UseGuards(AtGuard)
  @Get(':orderId')
  @ApiOperation({ description: 'Find order by id' })
  async findOrderById(
    @Body() trace: TraceDto,
    @Param('orderId') orderId: string,
  ) {
    return await handleRPCResponse(() =>
      this.amqpConnection.request<ResponseRPC<GetOrderByIdContract.Response>>({
        exchange: GetOrderByIdContract.exchange,
        routingKey: GetOrderByIdContract.topic,
        payload: { orderId, ...trace },
      }),
    )
  }

1. In the gateway controller i set @TransformRPCInterceptor, which intercepts data / error and return them as { data, error } object.
@TransformRPCResponse()
@Controller()
export class OrderReadController {
  constructor(private readonly queryBus: QueryBus) {}

  @RabbitRPC({
    exchange: GetOrderByIdContract.exchange,
    routingKey: GetOrderByIdContract.topic,
    queue: GetOrderByIdContract.queue,
  })
  public findOrderById({
    orderId,
  }: GetOrderByIdContract.Request): Observable<any> {
    // ...
  }
  2. @TransformRPCInterceptor implementation:
  export function TransformRPCResponse() {
  return UseInterceptors(TransformRPCResponseResponseInterceptor)
}
export type ResponseRPC<D> =
  | { data: D; error: null }
  | { data: null; error: StringError }

@Injectable()
export class TransformRPCResponseResponseInterceptor<D>
  implements NestInterceptor<D>
{
  intercept(
    _context: ExecutionContext,
    next: CallHandler,
  ): Observable<ResponseRPC<D>> {
    return next.handle().pipe(
      map((result) => {
        return { data: result, error: null }
      }),
      catchError((error: Error) => {
        let unwindError: Error

        if (error instanceof RpcException) {
          unwindError = error.getError() as Error
        } else {
          unwindError = error
        }

        return of({
          data: null,
          error: JSON.stringify({
            ...unwindError,
            message: unwindError?.message,
          }),
        })
      }),
    )
  }
}
3.

**Comment by Lormida** [comment]
Probably i'm completely wrong in it, but i can describe how i handle errors between microservices with RabbitMQ.
1. I use `api gateway pattern` this means i have single http entrypoint controller which redirect my initial requests to another microservices using RabbitMq. My workflow looks like:

(1) Controller gets http request (A) -> (2) Forward this request via rabbitMq to another ms (B) -> (3) This ms can either forward new request to another ms via rabbitmq or return result (C).

1. Gateway controller (A).
 @UseGuards(AtGuard)
  @Get(':orderId')
  @ApiOperation({ description: 'Find order by id' })
  async findOrderById(
    @Body() trace: TraceDto,
    @Param('orderId') orderId: string,
  ) {
    return await handleRPCResponse(() =>
      this.amqpConnection.request<ResponseRPC<GetOrderByIdContract.Response>>({
        exchange: GetOrderByIdContract.exchange,
        routingKey: GetOrderByIdContract.topic,
        payload: { orderId, ...trace },
      }),
    )
  }

2. In the (B) microservice consumer i set @TransformRPCInterceptor, which intercepts result / error from this method (findOrderById) and return them as { data, error } object. I do that in order to any ms using rabbitmq always returns data (even if this error thrown an error).
@TransformRPCResponse()
@Controller()
export class OrderReadController {
  constructor(private readonly queryBus: QueryBus) {}

  @RabbitRPC({
    exchange: GetOrderByIdContract.exchange,
    routingKey: GetOrderByIdContract.topic,
    queue: GetOrderByIdContract.queue,
  })
  public findOrderById({
    orderId,
  }: GetOrderByIdContract.Request): Observable<any> {
    // ...
  }
  2. @TransformRPCInterceptor implementation:
  export function TransformRPCResponse() {
  return UseInterceptors(TransformRPCResponseResponseInterceptor)
}
export type ResponseRPC<D> =
  | { data: D; error: null }
  | { data: null; error: StringError }

@Injectable()
export class TransformRPCResponseResponseInterceptor<D>
  implements NestInterceptor<D>
{
  intercept(
    _context: ExecutionContext,
    next: CallHandler,
  ): Observable<ResponseRPC<D>> {
    return next.handle().pipe(
      map((result) => {
        return { data: result, error: null }
      }),
      catchError((error: Error) => {
        let unwindError: Error

        if (error instanceof RpcException) {
          unwindError = error.getError() as Error
        } else {
          unwindError = error
        }

        return of({
          data: null,
          error: JSON.stringify({
            ...unwindError,
            message: unwindError?.message,
          }),
        })
      }),
    )
  }
}

3. Let's back to gateway controller (A). We see that we have another helper function `handleRPCResponse`. This function intercepts results as { data, error} and analyzes it in order to understand if this rabbitmq call returned error or data:
export function handleRPCResponse<T>(
  callback: (...args: any[]) => Promise<ResponseRPC<T>>,
): Promise<T> {
  return new Promise(async (resolve, reject) => {
    const response = await callback()

    if (response?.error) {
      // use rpc exeption intentionally in order to point out that it's rabbit mq exception
      reject(new RpcException(JSON.parse(response?.error)))
    }

    resolve(response?.data)
  })
}

4. Conclusion: each rabbitmq call is wrapped in @TransformRPCInterceptor which catch actual rabbitmq error or data and return it safely back as { data: any | null, error: Error | null }. Then in gateway controller we use `handleRPCResponse` function that unpack our result and return either real data (if data field is not null) or artificially throws new RPC exception (which is indeed HttpException). And already then in our root gateway controller we can use some RPCException filter in order to catch this error and return some result. We do all this complecated stuff because (as far as i know i hope you have better option) we can't just throw an error in some child microservice, we always should return "correct" result to the parent (gateway controller) ms.

**Comment by Skippia** [comment]
Probably i'm completely wrong in it, but i can describe how i handle errors between microservices with RabbitMQ.
1. I use `api gateway pattern` this means i have single http entrypoint controller which redirects my initial requests to another microservices using RabbitMq. My workflow looks like:
`(1) Controller gets http request (A) -> (2) Forwards this request via rabbitMq to another ms (B) -> (3) This ms can either forward new request to another ms via rabbitmq or return result (C).
`
1. Gateway controller (A).
 ```ts
 @UseGuards(AtGuard)
  @Get(':orderId')
  @ApiOperation({ description: 'Find order by id' })
  async findOrderById(
    @Body() trace: TraceDto,
    @Param('orderId') orderId: string,
  ) {
    return await handleRPCResponse(() =>
      this.amqpConnection.request<ResponseRPC<GetOrderByIdContract.Response>>({
        exchange: GetOrderByIdContract.exchange,
        routingKey: GetOrderByIdContract.topic,
        payload: { orderId, ...trace },
      }),
    )
  }
  ```

2. In the (B) microservice consumer i set `@TransformRPCInterceptor`, which intercepts result / error from this method (findOrderById) and return it as { data, error } object. I do that in order to return data (even if this method threw an error) back to the producer.
```ts
@TransformRPCResponse()
@Controller()
export class OrderReadController {
  constructor(private readonly queryBus: QueryBus) {}

  @RabbitRPC({
    exchange: GetOrderByIdContract.exchange,
    routingKey: GetOrderByIdContract.topic,
    queue: GetOrderByIdContract.queue,
  })
  public findOrderById({
    orderId,
  }: GetOrderByIdContract.Request): Observable<any> {
    // ...
  }
  ```
  
  2. `@TransformRPCInterceptor` implementation:
 ```ts
  export function TransformRPCResponse() {
  return UseInterceptors(TransformRPCResponseResponseInterceptor)
}
export type ResponseRPC<D> =
  | { data: D; error: null }
  | { data: null; error: StringError }

@Injectable()
export class TransformRPCResponseResponseInterceptor<D>
  implements NestInterceptor<D>
{
  intercept(
    _context: ExecutionContext,
    next: CallHandler,
  ): Observable<ResponseRPC<D>> {
    return next.handle().pipe(
      map((result) => {
        return { data: result, error: null }
      }),
      catchError((error: Error) => {
        let unwindError: Error

        if (error instanceof RpcException) {
          unwindError = error.getError() as Error
        } else {
          unwindError = error
        }

        return of({
          data: null,
          error: JSON.stringify({
            ...unwindError,
            message: unwindError?.message,
          }),
        })
      }),
    )
  }
}
```
3. Let's back to gateway controller (A). We see that we have another helper function `handleRPCResponse`. This function intercepts results as { data, error} and analyzes it in order to understand if this rabbitmq call returned error or data:
```ts
export function handleRPCResponse<T>(
  callback: (...args: any[]) => Promise<ResponseRPC<T>>,
): Promise<T> {
  return new Promise(async (resolve, reject) => {
    const response = await callback()

    if (response?.error) {
      // use rpc exeption intentionally in order to point out that it's rabbit mq exception
      reject(new RpcException(JSON.parse(response?.error)))
    }

    resolve(response?.data)
  })
}
```

4. `Conclusion:` each rabbitmq call is wrapped in `@TransformRPCInterceptor` which catches actual rabbitmq error or data and returns it safely back as { data: Data | null, error: Error | null }. Then in gateway controller we use `handleRPCResponse` function that unpacks this result and returns either real data (if data field is not null) or artificially throws `new RPC exception` (which is indeed HttpException). And already then in our `gateway controller` we can use some `RPCException filter` in order to catch this error and return some result to the client. 

`We do all this complicated stuff because (as far as i know i hope you have better solution) we can't just throw an error in some child microservice, we always should return "correct" result to the parent (gateway controller) ms, and the single way to achieve it - is to return just data and based on it - to decide if throw RPC exception or return real data`.
