### ISSUE TITLE
Unable to set the heartbeat to 0 from the client

### ISSUE THREAD

**Issue by mayurc137** [golevelup/nestjs#610]
Here is the rabbitMQ config

```
export const rabbitMQConfig = {
    uri: process.env['RABBITMQ_URI'] || 'amqp://guest:guest@localhost:5672',
    connectionInitOptions: { wait: false },
    connectionManagerOptions: { heartbeatIntervalInSeconds: 0 },
};
```

I am using a managed instance of rabbitMQ from cloudAMQP. I have set the heartbeat to zero from the server. Still the management dashboard shows the default 5 sec

![image](https://github.com/golevelup/nestjs/assets/1998238/47e0aca6-4b33-4c8f-a666-350473df0393)

**Comment by underfisk** [comment]
@mayurc137 There's nothing that this library does as it just forwards to the underlying amqlib library so I might recommend visiting the GH repo and seeing if there's any issue.
I might be able to assist you if you could provide a repro but I'm sure that eventually the issue is going to be in the underlying lib

**Comment by mayurc137** [comment]
I was able to resolve this by adding ?heartbeat=0 at the end of the RABBITMQ_URI

```
export const rabbitMQConfig = {
    uri: `${process.env['RABBITMQ_URI']}?heartbeat=0` || 'amqp://guest:guest@localhost:5672?heartbeat=0',
    connectionInitOptions: { wait: false },
    connectionManagerOptions: { heartbeatIntervalInSeconds: 0 },
};
```
