### ISSUE TITLE
@golevelup/ts-vitest

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [golevelup/nestjs#613]
would it be possible to make a similar `createMock` for vitest like in @golevelup/ts-jest? I guess it would be something like `%s/jest/vi/g` or something.

**Comment by underfisk** [comment]
@sschneider-ihre-pvs It is possible but `createMock` does only work with jest as you can see in the source. 
I've played with https://github.com/eratio08/vitest-mock-extended in the past and worked just fine, you might give it a shot but unfortunately Vitest came way after this library even exist 😅

**Comment by ikar1234** [comment]
Sorry, but I don't understand what the issue is. I copied the contents of the [mocks.ts](https://github.com/golevelup/nestjs/blob/master/packages/testing/ts-jest/src/mocks.ts) file, replaced all occurrences of `jest` with `vi`, and all tests are passing.

It's a single file, so it's not an issue for us to simply copy it to our codebases, but it would definitely be an improvement to have a separate package for this.

**Comment by jderochervlk** [comment]
Hi, we just did the same thing. It should be easy enough to add in a vitest file.

**Comment by jderochervlk** [comment]
Opened up a PR that adds support for Vitest: https://github.com/golevelup/nestjs/pull/702
