### ISSUE TITLE
Question: how I can get acces to my config from decorator config?

### ISSUE THREAD

**Issue by tttmaximttt** [golevelup/nestjs#622]
Question: how I can get acces to my config from decorator config?
![Screenshot 2023-07-14 at 20 18 58](https://github.com/golevelup/nestjs/assets/8621125/497857fd-b9ef-4736-b04f-83d63bc83ae3)

**Comment by tttmaximttt** [comment]
I want to get values for `queue` and `exchange` from config

**Comment by tttmaximttt** [comment]
same thing with validation, how I can put custom logger to log validation error ???
```typescript
  @RabbitRPC({
    routingKey: AccountRegister.topic,
    queue: 'account',
    exchange: 'account',
    createQueueIfNotExists: true,
    errorHandler: (channel: Channel, msg: ConsumeMessage, error: unknown) => {
      console.log('>>error', error)
      channel.ack(msg)
    }
  })
  @UsePipes(ValidationPipe)
  public async rpcHandler(@RabbitPayload() msg: AccountRegister.Request) {
    console.log(msg)
    return {
      response: 42
    }
  }
```

**Comment by tttmaximttt** [comment]
figured our but actualy this should be in examples
```@RabbitRPC({ name: 'rpcHandler' })```

**Comment by lisophoria** [comment]
> I want to get values for `queue` and `exchange` from config

Facing the same issue. How did you manage to do this?

**Comment by WonderPanda** [comment]
@lisophoria
 
Decorators are a special code construct that are evaluated at the time that the actual file is imported into your program. It is possible to pull in values into decorator config but you need to ensure that all your config values are validated and available in a variable before the file is imported. This makes it impossible to use the Nest Config system since by the time the DI container is bootstrapped all the decorators will have already been evaluated
