### ISSUE TITLE
Gracefully shutdown rabbitmq subscribers

### ISSUE THREAD

**Issue by ttshivers** [golevelup/nestjs#688]
It would be great if this was able to let rabbitmq subscribers gracefully shut down, meaning let them process any messages they currently have started and then shut down and close connections.

Perhaps implementing similar patterns to https://github.com/pasalino/nestjs-rabbitmq-transporter-graceful-shutdown/blob/main/src/graceful-server-rmq.ts

**Comment by underfisk** [comment]
@ttshivers It is possible to wire and i don't think it would require too much code

**Comment by vaidas-dutrys** [comment]
+1

**Comment by ttshivers** [comment]
Would we want to keep a list of consumer/subscriber promises, do something with rxjs, or just maintain a dumb count of outstanding messages and wait for a given time?

**Comment by nagorn** [comment]
Any update on this? We're facing the same issue when NestJS app get kill by OS User. the message that still in process within our application is gone forever. So, we explore 2 solution:
1) noAck = true
2) gracefule shutdown

for the first option is not support by this library but the bottom line is app manual control ack and if app lost connection to rabbitmq server than the server will requeue the message automatically

for second option the bottom line is app will not fetch any new message and wait until process all consumed message then die.

this is critical because we are trusted that all message (100%) that go though rabbitmq must be always get processed.

**Comment by underfisk** [comment]
> Would we want to keep a list of consumer/subscriber promises, do something with rxjs, or just maintain a dumb count of outstanding messages and wait for a given time?

Implementation details I'll leave up to your judgment and our consumers need

**Comment by ttshivers** [comment]
> Any update on this? We're facing the same issue when NestJS app get kill by OS User. the message that still in process within our application is gone forever. So, we explore 2 solution:
> 
> 1. noAck = true
> 2. gracefule shutdown
> 
> for the first option is not support by this library but the bottom line is app manual control ack and if app lost connection to rabbitmq server than the server will requeue the message automatically
> 
> for second option the bottom line is app will not fetch any new message and wait until process all consumed message then die.
> 
> this is critical because we are trusted that all message (100%) that go though rabbitmq must be always get processed.

If you must ensure that all messages are processed, then the only guaranteed way by rabbitmq is `noAck=false` and only acknowledge the messages after they have been processed.
Your application or host could die or lose power and graceful shutdowns wouldn't save you at all in that case if you had `noAck=true`.
