### ISSUE TITLE
ts-vitest: using with `vi.spyOn` isn't working

### ISSUE THREAD

**Issue by micalevisk** [golevelup/nestjs#737]
when we have a testing module like this:

![image](https://github.com/golevelup/nestjs/assets/13461315/86ef6ad8-252b-4752-a785-b2eb27a6b414)

using `vi.spyOn(productPriceRepository, 'findOne')` throws the following error:

![image](https://github.com/golevelup/nestjs/assets/13461315/b9f24203-32a6-4586-96a8-a6448cc38c7f)

While it works if we use a simple `vi.fn()` like this:

![image](https://github.com/golevelup/nestjs/assets/13461315/c32b7692-02bb-4ba9-9e8e-88459e0557dc)

**Comment by barraponto** [comment]
First, let's go all in with `useMocker`:

```typescript
const module = await Test
    .createTestingModule({ providers: [ProductPriceService] })
    .useMocker(createMock)
    .compile()
```

This will ensure `createMock` mocks all the dependencies. Adding dependencies will not break this test anymore 🥳 
Now, during your tests, you can do the following:

```typescript
const repository: DeepMocked<ProductPriceRepository> = module.get(ProductPriceRepository);
repository.findOne.mockResolvedValue(oneProductPrice);
```

The repository you get from `module.get` is already a mock, but Typescript does not know about it. That's why we declare the type as `DeepMocked<ProductPriceRepository>`. And since it is a mock, there's no need to spy on its methods: they're already stubs and do nothing. You can directly set the resolved value if you need to.

**Comment by micalevisk** [comment]
> there's no need to spy on its methods

but I'm using the spy to assert with `expect(spy).toBeCalledWith(..)`

I can use `repository.findOne` instead of the spy, I guess. But I'll leave this issue open because the _vi.spyOn_ seems to be not working(?) as it raises that error

**Comment by barraponto** [comment]
`repository.findOne` is a stub (does nothing), because `repository` itself is a mock.
`vi.spyOn` would be useful if you wanted the _actual_ method to be called, but it is no longer there to begin with.
