### ISSUE TITLE
RabbitMQModule doesn't have forRoot and forRootAsync methods

### ISSUE THREAD

**Issue by bakedChicken** [golevelup/nestjs#77]
Hi. I'm trying to implement custom message parsing and serializing feature for RabbitMQ module because I would like to exchange messages in XML format.

So far I have made necessary changes and trying to launch `integration/rabbitmq` example, but it doesn't have `@golevelup/nestjs-rabbitmq` dependency in `package.json` and it's also using forRootAsync method for module setup which doesn't exists.

I assume there is minor inconsistency between packages and I would like to create PR to fix it. Could you provide additional information about this?

**Comment by jmcdo29** [comment]
I think the `package.json` should have the `@golevelup/nestjs-rabbitmq` package. 

As for the missing `forRoot` and `forRootAsync` methods, they actually do exists, thanks to the `createConfigurableDynamicRootModule` class that the `RabbitModule` class extends. You can find the code for `createConfigurableDynamicRootModule` in the `@golevelup/nestjs-module` package.

**Comment by ssilve1989** [comment]
@jmcdo29 The issue is the typescript declarations are incorrect so any TS build will fail. The declaration as of `1.7.1` looks like 
```typescript
import { DiscoveryService } from '@golevelup/nestjs-discovery';
import { DynamicModule, OnModuleInit } from '@nestjs/common';
import { ExternalContextCreator } from '@nestjs/core/helpers/external-context-creator';
import { AmqpConnection } from './amqp/connection';
import { RabbitMQConfig } from './rabbitmq.interfaces';
declare const RabbitMQModule_base: import("../../modules/lib").IConfigurableDynamicRootModule<RabbitMQModule, RabbitMQConfig>;
export declare class RabbitMQModule extends RabbitMQModule_base implements OnModuleInit {
    private readonly discover;
    private readonly amqpConnection;
    private readonly externalContextCreator;
    private readonly logger;
    constructor(discover: DiscoveryService, amqpConnection: AmqpConnection, externalContextCreator: ExternalContextCreator);
    static build(config: RabbitMQConfig): DynamicModule;
    static attach(connection: AmqpConnection): DynamicModule;
    onModuleInit(): Promise<void>;
}
export {};
```

Causing 
```bash
../../../node_modules/@golevelup/nestjs-rabbitmq/lib/rabbitmq.module.d.ts:6:43 - error TS2307: Cannot find module '../../modules/lib'.
: 6 declare const RabbitMQModule_base: import("../../modules/lib").IConfigurableDynamicRootModule<RabbitMQModule, RabbitMQConfig>;
:                                             ~~~~~~~~~~~~~~~~~~~
: src/modules/entity-publisher/entity-publisher.module.ts:21:24 - error TS2339: Property 'forRootAsync' does not exist on type 'typeof RabbitMQModule'.
: 21         RabbitMQModule.forRootAsync({
:                           ~~~~~~~~~~~~
```

This line in particular is referencing a wrong path 
```
import("../../modules/lib").IConfigurableDynamicRootModule<RabbitMQModule, RabbitMQConfig>;
``` 
there is no `modules/lib` when installing this package in a project. its actually `nestjs-modules/lib` since its depdendent on the `nestjs-modules` package

**Comment by WonderPanda** [comment]
@ssilve1989 Thanks for providing this detail, I'll take a look at this issue tonight

**Comment by WonderPanda** [comment]
@ssilve1989 @bakedChicken Sorry the fix is now live for this in `@golevelup/nestjs-rabbitmq@1.7.2`

I don't fully understand why TS was generating that portion of the Typings with a relative path to `@goleveup/nestjs-modules` instead of pulling the Type from the NPM package.

Will have to do further investigation to see if there's improvements on my TS Lerna Monorepo setup to prevent this kind of thing in the future
