### ISSUE TITLE
routingKey is ignored

### ISSUE THREAD

**Issue by Ziao** [golevelup/nestjs#775]
Hi guys,

I'm encountering an issue with the RabbitMQ module. I have two subscribers listening on the same queue but with different routing keys. However, messages are being processed in a round-robin fashion between the handlers, regardless of the routing key.

Here's the code:

```ts
@RabbitSubscribe({
    exchange: 'asset.topic',
    routingKey: 'asset.index.success',
    queue: 'api.assetModule',
})
async onAssetIndexed(data: { caseId: number; assetId: number }) {
    this.logger.log(`Asset ${data.caseId}/${data.assetId} indexed successfully`);
}

@RabbitSubscribe({
    exchange: 'asset.topic',
    routingKey: 'asset.index.error',
    queue: 'api.assetModule',
})
async onAssetIndexError(data: { caseId: number; assetId: number; reason: string }) {
    this.logger.error(`Failed to index asset ${data.caseId}/${data.assetId}: ${data.reason}`);
}
```

I would have expected the routingKey to also be used by the library to call the right handler, as opposed to it only being used to bind the queue to certain keys.

Any advice would be appreciated!

**Comment by y-nk** [comment]
This is a misunderstanding with the nature of message queue systems. what you are describing is not what is happening. a very simple rule of thumb to remember is this:

**any handler listening to a queue will receive a message of the queue  in round robin fashion, regardless of the routing key.**

the binding you add when doing `@Subscriber({ routingKey: 'a', queue: 'a' })` does NOT imply that _this_ subscriber will ONLY receive messages coming from the routing key 'a'. it ONLY implies that, this subscriber will **ADD** ONE MORE routing key 'a' to the queue 'a'.

after that, if your queue has more than one routing key bound, it will receive multiple messages and each message will be blindly distributed to the handler **based on the queue**.

as a fundamental, the flow of RMQ is NOT:

```
publish → exchange → routing key → queue → routing key filtering → handler
```

BUT ONLY:

```
publish → exchange → routing key → queue → handler
```

here you can see the "filtering" you expect is **before** putting the message to the queue, describing what you are experiencing. there's no additional step after that to filter out based on the subscriber.

**Comment by Ziao** [comment]
That makes a lot of sense. Thank you for your thorough explanation ❤️.

**Comment by 6uliver** [comment]
> This is a misunderstanding with the nature of message queue systems. what you are describing is not what is happening. a very simple rule of thumb to remember is this:
> 
> **any handler listening to a queue will receive a message of the queue in round robin fashion, regardless of the routing key.**
> 
> the binding you add when doing `@Subscriber({ routingKey: 'a', queue: 'a' })` does NOT imply that _this_ subscriber will ONLY receive messages coming from the routing key 'a'. it ONLY implies that, this subscriber will **ADD** ONE MORE routing key 'a' to the queue 'a'.
> 
> after that, if your queue has more than one routing key bound, it will receive multiple messages and each message will be blindly distributed to the handler **based on the queue**.
> 
> as a fundamental, the flow of RMQ is NOT:
> 
> ```
> publish → exchange → routing key → queue → routing key filtering → handler
> ```
> 
> BUT ONLY:
> 
> ```
> publish → exchange → routing key → queue → handler
> ```
> 
> here you can see the "filtering" you expect is **before** putting the message to the queue, describing what you are experiencing. there's no additional step after that to filter out based on the subscriber.

But why? For me it does not make sense since I need to create different queues for every routing key. 
It's also confusing for other developers too, see:
https://github.com/golevelup/nestjs/issues/1053
https://github.com/golevelup/nestjs/issues/716

It would be intuitive to have this flow and this package would call the specific handler based on the routing key:

```
publish → exchange → routing key → queue → routing key filtering → handler
```

So that I could do something like for my microservice:

```
@RabbitSubscribe({
  exchange: 'events',
  routingKey: 'client.connected',
  queue: 'my-microservice-queue',
})
onConnected(){...}

@RabbitSubscribe({
  exchange: 'events',
  routingKey: 'client.disconnected',
  queue: 'my-microservice-queue',
})
onDisconnected(){...}
```

Can I send a PR for this?

**Comment by y-nk** [comment]
> But why?

what i explained is NOT the library's behavior but **it's how the amqp protocol is defined**. if you need ton complain somewhere, it's directly at the amqp spec, so it's at [amqplib](https://github.com/amqp-node/amqplib).

To expand on previous explanation:

```
publish → (exchange → routing key → queue) → routing key filtering → handler(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    AMQP SERVER
```

If we follow your idea, that would mean the routing key filtering is done after the message is delivered to your server, which would imply that **your server would be spammed with shit ton of unwanted messages to be able to filter them**... and that is why amqp doesn't work this way.

You have good material on the rabbitmq website, notably [here](https://www.rabbitmq.com/tutorials/amqp-concepts), or [here](https://www.rabbitmq.com/docs/consumers#priority) but i would expect any gpt to be able to converse and explain you in depth.

EDIT: https://chatgpt.com/share/68ca8ed8-37f0-8007-883b-5277fc973f5a

---

> So that I could do something like for my microservice:
> 
> ```
> @RabbitSubscribe({
>   exchange: 'events',
>   routingKey: 'client.connected',
>   queue: 'my-microservice-queue',
> })
> onConnected(){...}
> 
> @RabbitSubscribe({
>   exchange: 'events',
>   routingKey: 'client.disconnected',
>   queue: 'my-microservice-queue',
> })
> onDisconnected(){...}
> ```


Quick fix for your problem:

```diff
@RabbitSubscribe({
  exchange: 'events',
-  queue: 'my-microservice-queue',
+  queue: 'my-microservice-queue-connected',
})
onConnected(){...}

@RabbitSubscribe({
  exchange: 'events',
-  queue: 'my-microservice-queue',
+  queue: 'my-microservice-queue-disconnected',
})
onDisconnected(){...}
```

or:

```diff
@RabbitSubscribe({
  exchange: 'events',
  routingKey: 'client.disconnected',
  queue: 'my-microservice-queue',
})
- onConnected(){...}
+ onConnectedOrDisconnected(msg: any, amqp: AmqpMessage) {
+   const handler = {
+    'client.connected': () => this.onConnected(msg),
+    'client.disconnected': () => this.onDisconnected(msg),
+   }[amqp.fields.routingKey]
+
+   handler?.()
+ }

@RabbitSubscribe({
  exchange: 'events',
  routingKey: 'client.disconnected',
  queue: 'my-microservice-queue',
})
- onDisconnected(){...}
+ onConnectedOrDisconnected(msg: any, amqp: AmqpMessage) {
+   const handler = {
+    'client.connected': () => this.onConnected(msg),
+    'client.disconnected': () => this.onDisconnected(msg),
+   }[amqp.fields.routingKey]
+
+   handler?.()
+ }
+
+ onConnected() {}
+
+ onDisconnected() {}
```

which, with a topic exchange could be simplified in:

```ts
@RabbitSubscribe({
  exchange: 'events',
  routingKey: 'client.*',
  queue: 'my-microservice-queue',
})
onClientEvent(msg: any, amqp: AmqpMessage) {
  const handler = {
   'client.connected': () => this.onConnected(msg),
   'client.disconnected': () => this.onDisconnected(msg),
  }[amqp.fields.routingKey]

  handler?.()
}

onConnected() {}
onDisconnected() {}
```

**Comment by 6uliver** [comment]
> > But why?
> 
> what i explained is NOT the library's behavior but **it's how the amqp protocol is defined**. if you need ton complain somewhere, it's directly at the amqp spec, so it's at [amqplib](https://github.com/amqp-node/amqplib).
> 
> To expand on previous explanation:
> 
> ```
> publish → (exchange → routing key → queue) → routing key filtering → handler(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>                     AMQP SERVER
> ```
> 
> If we follow your idea, that would mean the routing key filtering is done after the message is delivered to your server, which would imply that **your server would be spammed with shit ton of unwanted messages to be able to filter them**... and that is why amqp doesn't work this way.
> 
> You have good material on the rabbitmq website, notably [here](https://www.rabbitmq.com/tutorials/amqp-concepts), or [here](https://www.rabbitmq.com/docs/consumers#priority) but i would expect any gpt to be able to converse and explain you in depth.
> 
> EDIT: https://chatgpt.com/share/68ca8ed8-37f0-8007-883b-5277fc973f5a
> 
> > So that I could do something like for my microservice:
> > ```
> > @RabbitSubscribe({
> >   exchange: 'events',
> >   routingKey: 'client.connected',
> >   queue: 'my-microservice-queue',
> > })
> > onConnected(){...}
> > 
> > @RabbitSubscribe({
> >   exchange: 'events',
> >   routingKey: 'client.disconnected',
> >   queue: 'my-microservice-queue',
> > })
> > onDisconnected(){...}
> > ```
> 
> Quick fix for your problem:
> 
> @RabbitSubscribe({
>   exchange: 'events',
> -  queue: 'my-microservice-queue',
> +  queue: 'my-microservice-queue-connected',
> })
> onConnected(){...}
> 
> @RabbitSubscribe({
>   exchange: 'events',
> -  queue: 'my-microservice-queue',
> +  queue: 'my-microservice-queue-disconnected',
> })
> onDisconnected(){...}
> or:
> 
> @RabbitSubscribe({
>   exchange: 'events',
>   routingKey: 'client.disconnected',
>   queue: 'my-microservice-queue',
> })
> - onConnected(){...}
> + onConnectedOrDisconnected(msg: any, amqp: AmqpMessage) {
> +   const handler = {
> +    'client.connected': () => this.onConnected(msg),
> +    'client.disconnected': () => this.onDisconnected(msg),
> +   }[amqp.fields.routingKey]
> +
> +   handler?.()
> + }
> 
> @RabbitSubscribe({
>   exchange: 'events',
>   routingKey: 'client.disconnected',
>   queue: 'my-microservice-queue',
> })
> - onDisconnected(){...}
> + onConnectedOrDisconnected(msg: any, amqp: AmqpMessage) {
> +   const handler = {
> +    'client.connected': () => this.onConnected(msg),
> +    'client.disconnected': () => this.onDisconnected(msg),
> +   }[amqp.fields.routingKey]
> +
> +   handler?.()
> + }
> +
> + onConnected() {}
> +
> + onDisconnected() {}
> which, with a topic exchange could be simplified in:
> 
> @RabbitSubscribe({
>   exchange: 'events',
>   routingKey: 'client.*',
>   queue: 'my-microservice-queue',
> })
> onClientEvent(msg: any, amqp: AmqpMessage) {
>   const handler = {
>    'client.connected': () => this.onConnected(msg),
>    'client.disconnected': () => this.onDisconnected(msg),
>   }[amqp.fields.routingKey]
> 
>   handler?.()
> }
> 
> onConnected() {}
> onDisconnected() {}

Thanks for your helpful response! I can also chat with ChatGPT and link documents to you but that wouldn't solve the badly designed, misleading interface.

I didn't talk about how AMQP is working, I exactly know what's happening. As you also described:

```
publish → (exchange → routing key → queue) → routing key filtering → handler(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    AMQP SERVER
```

So the routing key filtering does not happen in the AMQP layer, what I'm saying is that it **should happen in this library** because that would be intuitive for the user of the library. Something like this:

```
publish → (exchange → routing key → queue) → routing key filtering → handler(s)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     this library
```

I guess you've vibe coded the suggested solution to create inline handlers in my Schrödinger handlers named onConnectedOrDisconnected, I guess if I would have 15 different events on the same queue my method name should be extremely long.

It's also a good idea to create an inline handler selection logic inside every handler, it's a very good DX. Maybe it would be a great idea to create a package which can map handler methods with decorators based on the incoming routing key! Hm, wait...

To be serious, you mentioned: "your server would be spammed with shit ton of unwanted messages to be able to filter them."
It looks like you don't understand the usage pattern of this library. You don't bind an exchange with a routing key to a queue if you don't add a RabbitSubscribe decorator. If you do that means your microservice is interested in this message and this instance of the service can potentially process it. It wouldn't be spammed of unwanted messages, they are very wanted by the microservice, that's the point. Your wilcard "solution" would spam the service: `routingKey: 'client.*'`
Thanks for your link, it says: "Normally, active consumers connected to a queue receive messages from it in a round-robin fashion." That's the point of the competing consumers pattern that I would like to implement with this library, for every microservice I define a dedicated queue and the instances of this microservices are competing consumers.

If I would write this:

```
@RabbitSubscribe({
  exchange: 'events',
  routingKey: 'client.connected',
  queue: 'my-microservice-queue',
})
onConnected(){...}

@RabbitSubscribe({
  exchange: 'events',
  routingKey: 'client.disconnected',
  queue: 'my-microservice-queue',
})
onDisconnected(){...}
```

I would like to instruct the library to do the following:

- bind "events" exchange with the "client.connected" routing key to the "my-microservice-queue"
- bind "events" exchange with the "client.disconnected" routing key to the "my-microservice-queue"
- if the library receives a message with the "client.connected" routing key from the "my-microservice-queue" call the onConnected message handler
- if the library receives a message with the "client.disconnected" routing key from the "my-microservice-queue" call the onDisconnected message handler

So that I would not need to copy-paste your handler selection logic but the library would handle this internally.

So should I send a PR for this or do I need to fork or write a new library?

PS: any maintainer here?

**Comment by WonderPanda** [comment]
@6uliver I'm torn about this because as discussed this is just how AMQP works as a protocol. I do think that there should be some expectation that developers learn the underlying technology. However, this has continuously been one of the biggest stumbling blocks and repeated issues that gets raised in the repo because as you you've pointed out, people see the decorator and expect that its going to behave differently.

Just to solidify my own understanding of your use case, what is the reason that you can't define a queue per event to get the behavior you want instead of expecting that you can re-use the same queue and then bind it to multiple routing keys?

If you feel really passionate about this and want to add server side filtering so that we add our own additional filtering logic I'm open to adding it as long as there's test coverage and we can point people in the right direction with some docs on it

**Comment by y-nk** [comment]
@6uliver 

<details>
<summary>I had written the below before, but re-reading myself, answer should be: just write your own library. Your message is not a "where am i wrong" but "you're wrong. should i fork this or go my way?", so i think whatever we say you won't be satisfied.</summary>

<br>

> I can also chat with ChatGPT and link documents to you but that wouldn't solve the badly designed, misleading interface.

\+

> I guess you've vibe coded the suggested solution to create inline handlers in my Schrödinger handlers named onConnectedOrDisconnected, I guess if I would have 15 different events on the same queue my method name should be extremely long.

the tone of those is debatable. using sarcasm when people try to help you isn't the way to keep a conversation constructive. you can keep "vibe coding guesses" comments for yourself, they're not constructive and dont carry any point except (failed) mockery.

Again the interface is not designed badly, it's just following amq protocol and does not add features on top.

---

> It's also a good idea to create an inline handler selection logic inside every handler, it's a very good DX. Maybe it would be a great idea to create a package which can map handler methods with decorators based on the incoming routing key! Hm, wait...

the implementation proposed was made to prove the point: if you wanna do it, you can on your own **very easily** ; but scaling this to an abstract library brings a lot more cases than this one with more complexity. Also, imho wrong from architectural design PoV (more on that below)

---

> To be serious, you mentioned: "your server would be spammed with shit ton of unwanted messages to be able to filter them."
> It looks like you don't understand the usage pattern of this library. You don't bind an exchange with a routing key to a queue if you don't add a RabbitSubscribe decorator. 
>If you do that means your microservice is interested in this message and this instance of the service can potentially process it. It wouldn't be spammed of unwanted messages, they are very wanted by the microservice, that's the point. Your wilcard "solution" would spam the service: routingKey: 'client.*'

I do understand very well thank you, both amqp and your expectations but I think you're adding complexity where there's no need to be.

Having dedicated queue per message is cheap and you're unlikely to treat side features such as dlx the same way depending on the message type anyway.

From code structure PoV, it's basically the same as separating algorithms/responsibilities per function (use 2) instead of creating a single function which does 2 things with 2 possible payloads as input.

From amqp architectural PoV, each queue could (should?) be seen as to be consumed by different (fleets of) workers which (each) have a dedicated purpose. **The unit is rather the job than the process which executes the job.** 

Otherwise said, imho your usecase is simple enough that you think "i have one service, i need one queue", which wrongly simplifies your view on how to model properly your feature (this is emphasized by the fact that the queue in your example is named `my-microservice-queue` rather than a job name...)

You have one service, it's true, but **you have 2 distinct job workers inside this service** and this is where the distribution to queue should be ; it just happens that those workers are each in the same docker container for once, maybe even the same controller and so "it looks leaner this way". I've been there, so I understand (and now we have 20 queues instead of 1 with a switch/case)

Promoting reusing queues between jobs makes me think it could go further and you may promote reusing queue between services... for which a service A could indeed receive messages intended for a service B (may or may not be shit ton of them). It sounds like a stupid construct I know, but why not just use one queue per job then uh?

---

> I would like to instruct the library to do the following:
> - bind "events" exchange with the "client.connected" routing key to the "my-microservice-queue"
> - bind "events" exchange with the "client.disconnected" routing key to the "my-microservice-queue"
> - if the library receives a message with the "client.connected" routing key from the "my→ microservice-queue" call the onConnected message handler
> - if the library receives a message with the "client.disconnected" routing key from the "my-microservice-queue" call the onDisconnected message handler

In the current implementation, as mentioned it's a (thin) wrapper around `channel.consume` but _more or less_ a 1-1 binding between a `@RabbitSubscribe` and a `channel.consume` function. You can follow quickly the trail from `rabbitmq.module.ts#onApplicationBootstrap` which has at the bottom a `Promise.all` to a `setupHandler` function, ultimately leading to `amqp/connection.ts#setupSubscriberChannel` which does the `channel.consume` call. 

What (i think) you're describing breaks that (partially, at least). We'd need to implement a routing function which would be added inside each `channel.consume` and which would find possible competing routing keys matching a topic and distribute the calls in round robin (all post-delivery).

It implies that this routing function should implement a full lib-side routing solution that matches the spec of exchange routing for all the types of exchanges _and_ keep track of handler subscriptions + past calls to handle the round robin distribution (if case need be). 

Then we'd bump into bending the exchange routing spec for better UX. For example, without opinionated changes to the spec, consider the following usecase brought by another user:

```ts
@RabbitSubscribe({
  exchange: 'events',
  routingKey: 'client.*',
  queue: 'my-microservice-queue',
})
onWhatever1(){...}

@RabbitSubscribe({
  exchange: 'events',
  routingKey: 'client.disconnected',
  queue: 'my-microservice-queue',
})
onDisconnected(){...}
```

When `client.disconnected` message is received, it would still be distributed in round robin when because the `client.*` also matches the `client.disconnected` topic. It'd be shit, right? But it's the amqp spec, so either - as mentioned before - you need to go complain to amqp spec for such, or...

To solve that, we'd need to introduce a rule such as "exact match beats wildcard" which, while could be seen as an improvement, would also does not reflect how topic exchange routing works and therefore **mess with how amqp is in the mind of people** (otherwise said, if somebody leaves golevelup and go play with amqp in any other setup they'd be for hours like "why it doesn't work as before")

None of this is good and rational when y**ou can either use 2 queues if you need parallel processing or use 1 queue and a simple if/else if you need sequential processing of your 2 events.**

</details>

---

@WonderPanda 

after thinking about the usecase from the example provided, the only legit usecase I see for `client.connected` and `client.disconnected` bound to the same queue is the wish to process them in sequence rather than in parallel. It could be because the handler of `client.connected` processes much faster than `client.disconnected` (or vice versa) leading to non representative state of the client (connected/disconnected) or derivate values.

If so i guess it's equally possible to `publish('events', 'client.connectionStateChanged', { connected: boolean })` which makes also a single queue to be handled with a `if (message.connected) { onConnected() } else { onDisconnected() }`
