### ISSUE TITLE
`publish` method lost generic type parameter in `@golevelup/nestjs-rabbitmq@5.5.0`

### ISSUE THREAD

**Issue by lzw1926** [golevelup/nestjs#792]
The `AmqpConnnection.publish` method lost generic type parameter support in the recent release, noticed by a TS transpile error of my project.
Is this an intentionally change which is confusing to me.

**Comment by underfisk** [comment]
@y-nk Can you help out here?

**Comment by y-nk** [comment]
@underfisk sure.

@lzw1926 could you show your usage of the generic? I'm asking because I'm responsible for its removal, therefore I would like to understand how you used it. I asked for its removal because it was not useful at all since the generic went into a `any` message afterwards.

I would be more than happy to revert (and maybe catch a way to use it properly on the go)

**Comment by lzw1926** [comment]
@y-nk Accually just for ts intellisense and type safety, the usage is simple currentlly cause I'm not a ts pro. Basically like the following code 
```ts
interface TaskQuery {
  taskId: string;
  userId: string;
}

@RabbitSubscribe({
  exchange: DELAYED_EXCHANGE,
  routingKey: ROUTING_KEY,
  queue: QUEUE_NAME,
  createQueueIfNotExists: true,
})
async queryTask(msg: TaskQuery, _: ConsumeMessage) {
  ...
}

async someMethod() {
  ... // get taskId and userId
  this.amqp.publish<TaskQuery>(DELAYED_EXCHANGE, ROUTING_KEY,
   {
     taskId,
     userId,
   },
   {
    headers: {
      'x-delay': 3000,
      [MQ_HEADER_TRACE_ID]: this.clsService.getId(),
    },
    persistent: true,
  });
}
```
I'm used to this practice and haven't go further with the generic so far.

**Comment by y-nk** [comment]
I had in mind that this is the only usage of the generic you can make.

If you want that that I revert on it, I don't mind and I apologize for the changes, as this is exactly something @underfisk was afraid of.

Otherwise, you can build the object in advance:

```ts
async someMethod() {
  const taskQuery: TaskQuery = { taskId, userId }

  ... // get taskId and userId
  this.amqp.publish<TaskQuery>(DELAYED_EXCHANGE, ROUTING_KEY, taskQuery {
    headers: {
      'x-delay': 3000,
      [MQ_HEADER_TRACE_ID]: this.clsService.getId(),
    },
    persistent: true,
  });
}
```

which works exactly the same. 

I'm trying to iterate on typing properly the publish function. So far (where I work) we settled for:

```ts
// user defined
type Publish = {
  '': {
    'some.event': SomePayload
  }
}

declare function publish<
  Exchange extends keyof Publish,
  RoutingKeys extends keyof Publish[Exchange],
>(
  exchange: Exchange,
  routingKey: RoutingKeys,
  payload: Publish[Exchange][RoutingKeys],
  opts?: Options.Publish
): Promise<boolean>
```

the more we're digging into this pattern and the more we're thinking the best would be for `AmqpConnection` to accept an optional generic. Default value of this generic could be 

```ts
type DefaultPublish = Record<string, Record<string, any>>
```

**Comment by lzw1926** [comment]
@y-nk I generally get it that you are working on a event mapped types like solution, glad to have that too. I think maybe it requires more voice to do the revert and it's ok to remain for now.

**Comment by underfisk** [comment]
@y-nk Quick curiosity: How do you guys handle runtime validation when doing type augmentation? (e.g: types are infered from a zod schema, its easy to read the schema if the client has access and validate it at runtime)

**Comment by y-nk** [comment]
@underfisk since all events sent on our exchanges are internal to our platforms we dont mind leaving no validation at subscriber level since we enforce validation at build at sender level - otherwise said: you can't send if you dont abide to the types, therefore the underlying promise is that the receiving messages are always correct.

if it was a different paradigm i would complement with a dto and - why not - add a validation pipe + auto error handler from the options (which would probably send to dlx)

**Comment by underfisk** [comment]
I see, the reason why i asked is that if you had a way to replay your events or manually produce them, there's no guarantee that outside your producer the data is correct.

**Comment by underfisk** [comment]
I'm closing this issue as there's no action item, if more people asks for the generic support again instead of being "forced" to use type-augmentation, we can provide a revert.
@y-nk maybe we can update the documentation with  type-augmentation examples to guide our rmq users better
